version: '3.9'

services:
  dbclase:
    image: postgres:15-alpine
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_DB=ejemplo1
      - POSTGRES_USER=quinto
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pg_dbclase:/var/lib/postgresql/data/pgdata
    networks:
      - net_dbclase

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=kam.santana@yavirac.edu.ec
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "8080:80"
    volumes:
      - pg_pgadmin_data:/var/lib/pgadmin
    networks:
      - net_dbclase

volumes:
  pg_dbclase:
    external: true
  pg_pgadmin_data:

networks:
  net_dbclase:
    external: true