name: Python application start

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Ejecutar la aplicación
        run: |
          python app.py

      - name: Test with pytest
        run: |
          pytest test_app.py

      - name: simulacion del deploy
        run: |
          echo "Simular que se esta desplegando.."

      - name: Construir la imagen de docker
        run: docker build -t ghcr.io/kamsantana/hello-kevin:1.0.0 .

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: publicar la imagen
        run: |
          docker push ghcr.io/kamsantana/hello-kevin:1.0.0